const books=[
{id:1,title:"Atomic Habits",author:"James Clear",genre:"Self-help",rating:4.8,pages:320,year:2018,mood:"Self-growth",desc:"An easy and proven way to build good habits and break bad ones.",cover:"https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg"},
{id:2,title:"The Midnight Library",author:"Matt Haig",genre:"Fiction",rating:4.5,pages:304,year:2020,mood:"Emotional",desc:"Between life and death there is a library, and within that library, another life.",cover:"https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg"},
{id:3,title:"Dune",author:"Frank Herbert",genre:"Science Fiction",rating:4.6,pages:688,year:1965,mood:"Adventure",desc:"A sweeping science-fiction epic of power, ecology, destiny and survival.",cover:"https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg"},
{id:4,title:"It Ends with Us",author:"Colleen Hoover",genre:"Romance",rating:4.4,pages:384,year:2016,mood:"Romance",desc:"A powerful contemporary story about love, choices and finding courage.",cover:"https://covers.openlibrary.org/b/isbn/9781501110368-L.jpg"},
{id:5,title:"The Seven Husbands of Evelyn Hugo",author:"Taylor Jenkins Reid",genre:"Fiction",rating:4.7,pages:400,year:2017,mood:"Emotional",desc:"A reclusive Hollywood icon finally tells the story of her extraordinary life.",cover:"https://covers.openlibrary.org/b/isbn/9781501161933-L.jpg"},
{id:6,title:"Project Hail Mary",author:"Andy Weir",genre:"Science Fiction",rating:4.7,pages:496,year:2021,mood:"Adventure",desc:"A lone astronaut wakes up with a mission that could save humanity.",cover:"https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg"},
{id:7,title:"Deep Work",author:"Cal Newport",genre:"Self-help",rating:4.5,pages:304,year:2016,mood:"Self-growth",desc:"Rules for focused success in a distracted world.",cover:"https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg"},
{id:8,title:"The Silent Patient",author:"Alex Michaelides",genre:"Thriller",rating:4.3,pages:336,year:2019,mood:"Thriller",desc:"A shocking psychological mystery about a woman who refuses to speak.",cover:"https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg"}
];
const authors=[["James Clear","JC","Habits, productivity & personal growth"],["Matt Haig","MH","Fiction, life & contemporary stories"],["Frank Herbert","FH","Science fiction & world-building"],["Colleen Hoover","CH","Romance & contemporary fiction"],["Andy Weir","AW","Science fiction & adventure"],["Cal Newport","CN","Productivity & focused work"],["Alex Michaelides","AM","Mystery & psychological thrillers"],["Taylor Jenkins Reid","TR","Fiction & historical stories"]];

function bookCard(b){return `<article class="book-card"><a href="book.html?id=${b.id}"><div class="cover" style="background-image:url('${b.cover}')"></div></a><div class="book-info"><b>${b.title}</b><small>${b.author}</small><div class="rating">★★★★★ ${b.rating}</div><button class="add-btn" onclick="addBook(${b.id})">＋ Add to Library</button></div></article>`}
function addBook(id){let arr=JSON.parse(localStorage.getItem("bookverseLibrary")||"[]");if(!arr.includes(id))arr.push(id);localStorage.setItem("bookverseLibrary",JSON.stringify(arr));alert("Added to your BookVerse library!")}
function addToLibrary(){let id=new URLSearchParams(location.search).get("id")||1;addBook(Number(id))}
function favoriteBook(){alert("Added to Favorites ♡")}
function subscribe(e){e.preventDefault();alert("You're subscribed to BookVerse weekly recommendations!")}
function goSearch(){let q=document.getElementById("globalSearch").value.trim();if(q)location.href="discover.html?q="+encodeURIComponent(q);else location.href="discover.html"}
function initTheme(){let dark=localStorage.getItem("bvTheme")==="dark";document.body.classList.toggle("dark",dark);let b=document.getElementById("themeBtn");if(b)b.textContent=dark?"☀":"☾"}
function initMenu(){let btn=document.getElementById("menuBtn"),nav=document.getElementById("nav");if(btn)btn.onclick=()=>{nav.style.display=nav.style.display==="flex"?"none":"flex";nav.style.position="absolute";nav.style.top="74px";nav.style.left="0";nav.style.right="0";nav.style.background=getComputedStyle(document.body).getPropertyValue("--surface");nav.style.padding="18px";nav.style.flexDirection="column";nav.style.boxShadow="0 12px 25px rgba(0,0,0,.1)"}}
document.addEventListener("DOMContentLoaded",()=>{initTheme();initMenu();let tb=document.getElementById("themeBtn");if(tb)tb.onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("bvTheme",document.body.classList.contains("dark")?"dark":"light");tb.textContent=document.body.classList.contains("dark")?"☀":"☾"};let tr=document.getElementById("trending");if(tr)tr.innerHTML=books.slice(0,6).map(bookCard).join("");let grid=document.getElementById("bookGrid");if(grid)initDiscover();let lib=document.getElementById("libraryBooks");if(lib){let ids=JSON.parse(localStorage.getItem("bookverseLibrary")||"[]");lib.innerHTML=(ids.length?books.filter(b=>ids.includes(b.id)):books.slice(0,4)).map(bookCard).join("")}let ag=document.getElementById("authorGrid");if(ag)renderAuthors(authors);let dc=document.getElementById("detailTitle");if(dc)initDetail();initQuiz()});
function initDiscover(){let grid=document.getElementById("bookGrid"),search=document.getElementById("bookSearch"),chips=document.querySelectorAll(".chip"),params=new URLSearchParams(location.search);if(params.get("q"))search.value=params.get("q");let active=params.get("genre")||params.get("mood");function render(){let q=search.value.toLowerCase(),f=document.querySelector(".chip.active")?.dataset.filter||"all";let list=books.filter(b=>(!q||(b.title+" "+b.author+" "+b.genre).toLowerCase().includes(q))&&(f==="all"||b.genre===f||b.mood===f)||(active&&(b.genre===active||b.mood===active)));document.getElementById("resultsCount").textContent=list.length+" books found";grid.innerHTML=list.length?list.map(bookCard).join(""):"<div class='empty'>No books found. Try another search.</div>"}search.oninput=render;chips.forEach(c=>c.onclick=()=>{chips.forEach(x=>x.classList.remove("active"));c.classList.add("active");active=null;render()});render()}
function initDetail(){let id=Number(new URLSearchParams(location.search).get("id")||1),b=books.find(x=>x.id===id)||books[0];document.title=b.title+" — BookVerse";document.getElementById("detailCover").style.backgroundImage=`url('${b.cover}')`;document.getElementById("detailGenre").textContent=b.genre.toUpperCase();document.getElementById("detailTitle").textContent=b.title;document.getElementById("detailAuthor").textContent="by "+b.author;document.getElementById("detailRating").textContent="★★★★★ "+b.rating+"  ·  1,240 reviews";document.getElementById("detailPages").textContent=b.pages+" pages";document.getElementById("detailYear").textContent="Published "+b.year;document.getElementById("detailDesc").textContent=b.desc;document.getElementById("detailAbout").textContent=b.desc+" BookVerse readers can save it to a personal shelf, track progress, rate the experience and share a review with the community.";document.getElementById("similar").innerHTML=books.filter(x=>x.id!==b.id&&x.genre===b.genre).slice(0,4).map(bookCard).join("")}
function renderAuthors(list){document.getElementById("authorGrid").innerHTML=list.map(a=>`<article class="author-card"><div class="author-avatar">${a[1]}</div><h3>${a[0]}</h3><p>${a[2]}</p><a class="btn" href="discover.html?q=${encodeURIComponent(a[0])}">View books</a></article>`).join("")}
function filterAuthors(q){renderAuthors(authors.filter(a=>a[0].toLowerCase().includes(q.toLowerCase())))}
const questions=[["What are you looking for today?",["A cozy escape","A big adventure","A new perspective","A thrilling mystery"]],["Which genres do you enjoy?",["Fiction","Self-help","Fantasy","Mystery & Thriller"]],["How much time do you have?",["Under 20 minutes","20–60 minutes","An hour or more","A whole weekend"]],["What do you prefer?",["Fiction","Non-fiction","A mix","I don't mind"]],["What energy do you want?",["Relaxing","Emotional","Intense","Inspiring"]]];
let qi=0;function initQuiz(){if(!document.getElementById("quiz"))return;showQuestion()}function showQuestion(){let q=questions[qi];document.getElementById("stepText").textContent=`Question ${qi+1} of ${questions.length}`;document.getElementById("progress").style.width=((qi+1)/questions.length*100)+"%";document.getElementById("quiz").innerHTML=`<h2>${q[0]}</h2><div class="quiz-options">${q[1].map((x,i)=>`<button class="quiz-option" onclick="selectQuiz(this)">${x}</button>`).join("")}</div>`}function selectQuiz(el){document.querySelectorAll(".quiz-option").forEach(x=>x.classList.remove("selected"));el.classList.add("selected")}function nextQuestion(){if(qi<questions.length-1){qi++;showQuestion()}else{document.getElementById("quiz").innerHTML="<h2>Your reading personality is ready ✦</h2><p>Based on your answers, we found a shelf with thoughtful, engaging and highly rated books.</p><div class='book-grid'>"+books.slice(0,4).map(bookCard).join("")+"</div>";document.getElementById("nextBtn").style.display="none"}}
function login(e){e.preventDefault();localStorage.setItem("bookverseLoggedIn","true");alert("Demo login successful!");location.href="library.html"}function signup(e){e.preventDefault();alert("This is a static frontend demo. Connect a backend later for real accounts.")}